{% set name = "conda-forge-metadata" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-forge-metadata/archive/refs/tags/{{ version }}.zip
  sha256: 266cf0f5ae7e61c15c7b8e816dcc4dd945853667fab786afef943c10adc89fde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm >=7
  run:
    - python >=3.6
    - requests
    - ruamel.yaml
    - conda-oci-mirror

test:
  imports:
    - conda_forge_metadata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/regro/conda-forge-metadata
  summary: programatic access to conda-forge's metadata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
