{% set name = "conda-forge-metadata" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-forge-metadata/archive/refs/tags/{{ version }}.zip
  sha256: 3bb366581fb470c75186f4240c818b7134a43f33b1c6e524ed0b0be22804176e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm >=7
  run:
    - python >=3.6
    - requests
    - pyyaml

test:
  imports:
    - conda_forge_metadata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/regro/conda-forge-metadata
  summary: programatic access to conda-forge's metadata
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
